### ISSUE TITLE
Can't start pyrl.py because of 'f' before strings.

### ISSUE THREAD

**Issue by deeredman1991** [velit/pyrl#4]
There are a bunch of 'f' s before strings. At first I thought it was a typo and removed it, but I keep seeing it.

for example
-in pyrl/main.py : line 97
`assert False, f"Unknown output {options.output}"`

-in pyrl/generic_algorithms.py : line 8
`assert x in old_range, f"Value '{x}' is not inside {old_range}"`
`assert len(old_range) > 1, f"Number {old_range.start} is not a range"`

in pyrl/creature/creature.py
`return f"Creature(name={self.name})"`

is there a dependency that I missed/looked over or wasn't included in the readme or requirements.txt?

Edit:
I think those were the only 4 so far as it started up after I removed them...but if there are more of them python hasn't seen yet; it could still cause issues.

**Comment by velit** [comment]
Yeah, the project is currently using python 3.6 as the interpreter version.
I recently updated the readme about this.

**Comment by velit** [comment]
Ultimately if I get the game near a stage where it's worth trying to get
people to actually play it (ie. it includes any actual gameplay...) I'll
probably release packages of the game that include the python interpreter
used (for example using pyinstaller) so the user only has to download the
release package and run it.

On Fri, Feb 2, 2018 at 2:30 PM, Tapani Kiiskinen <tapani.kiiskinen@gmail.com

**Comment by deeredman1991** [comment]
Well, I am using python36 ... O_O it's still throwing errors...

**Comment by velit** [comment]
You might have Python 3.6 installed but might be inadvertently using another python version to run the game. F-strings are a feature introduced in Python 3.6.
