### ISSUE TITLE
Found 2 bugs involving teleporting to the downstairs.

### ISSUE THREAD

**Issue by deeredman1991** [velit/pyrl#5]
1). The player can use 'X' to find the downstairs even if the downstairs is undiscovered.

2). The player can use 'X' or 'x' to teleport out of danger.

**Comment by velit** [comment]
Yes, this is intended. The game is currently not nearing a release stage.
I'm currently brainstorming ideas about the setting the game is going to
take and what kind of gameplay I want out of the game. Mostly everything in
it is just there to test all the different features of the engine and the
x/X functionality makes it easier to traverse levels.

**Comment by deeredman1991** [comment]
Yeah, I kinda figured that out when I went down to floor 99 from level one and was still one hitting mobs...lol :)
